// This file is generated by app/copy/codegen/utils/generateCopyType.ts
export type Copy = {
  homePageMetaTagTitle: string
  homePageTitle: string
  getStarted: string
  createdBy: string
  language: string
  law: string
  history: string
  georgian: string
  restart: string
  testPageTitle: (variables: { category: string }) => string
  categoryPageTitle: (variables: { category: string }) => string
  startTest: string
  markAsLearned: string
  learned: string
  homePageMetaTagDescription: string
  categoryPageMetaTagTitle: (variables: { category: string }) => string
  categoryPageMetaTagDescription: (variables: { category: string }) => string
  categoryTestPageMetaTagTitle: (variables: { category: string }) => string
  categoryTestPageMetaTagDescription: (variables: {
    category: string
  }) => string
}
