// This file is generated by app/copy/codegen/utils/generateCopyType.ts
export type Copy = {
  homePageMetaTagTitle: string
  homePageMetaTagDescription: string
  categoryPageMetaTagTitle: (variables: { category: string }) => string
  categoryPageMetaTagDescription: (variables: { category: string }) => string
  categoryTestPageMetaTagTitle: (variables: { category: string }) => string
  categoryTestPageMetaTagDescription: (variables: {
    category: string
  }) => string
}
