// This file is generated by app/copy/codegen/utils/generateGetCopy.ts
import { Language } from '@georgian/languages/Language'
import en from './en'
import ru from './ru'
import ka from './ka'

const copy = { en, ru, ka } as const

export const getCopy = (language: Language) => copy[language]
