// This file is generated by app/copy/codegen/utils/generateCopy.ts
import { Copy } from './Copy'
import { injectVariables } from '@georgian/utils/injectVariables'
export const ruCopy: Copy = {
  homePageMetaTagTitle: `Подготовка к экзамену на гражданство Грузии: руководства по языку, праву, истории и практические тесты`,
  homePageTitle: `Сдайте экзамен на гражданство Грузии уверенно!`,
  getStarted: `Начать`,
  createdBy: `Сделано`,
  language: `Язык`,
  law: `Закон`,
  history: `История`,
  georgian: `грузинский`,
  restart: `Перезапуск`,
  testPageTitle: (variables: { category: string }) =>
    injectVariables(`Грузинский тест {{category}}`, variables),
  categoryPageTitle: (variables: { category: string }) =>
    injectVariables(`Грузинские билеты {{category}}`, variables),
  startTest: `Начать тест`,
  markAsLearned: `отметить как изученное`,
  learned: `Научился`,
  homePageMetaTagDescription: `Получите превосходный результат на экзамене на гражданство Грузии с помощью наших комплексных учебных пособий, практических тестов и ресурсов, специально разработанных для достижения успеха в языке, праве и истории. Начните готовиться сегодня!`,
  categoryPageMetaTagTitle: (variables: { category: string }) =>
    injectVariables(
      `Подготовьтесь к экзамену на получение гражданства Грузии {{category}}: билеты на {{category}} и практические тесты`,
      variables,
    ),
  categoryPageMetaTagDescription: (variables: { category: string }) =>
    injectVariables(
      `Сдайте экзамен на получение гражданства Грузии {{category}} на отлично с нашими подробными учебными пособиями, практическими тестами и ресурсами, специально разработанными для достижения успеха в {{category}}. Начните готовиться сегодня!`,
      variables,
    ),
  categoryTestPageMetaTagTitle: (variables: { category: string }) =>
    injectVariables(
      `Проверьте свои знания по экзамену на грузинское гражданство {{category}}`,
      variables,
    ),
  categoryTestPageMetaTagDescription: (variables: { category: string }) =>
    injectVariables(
      `Проверьте свои знания на экзамене по гражданству Грузии {{category}} с помощью наших практических тестов {{category}}. Начните готовиться сегодня!`,
      variables,
    ),
}
