// This file is generated by app/copy/codegen/utils/generateCopyType.ts
export type Copy = {
  introduction: string
  education: string
  origin: string
  signIn: string
  account: string
  work: string
  residence: string
  citizenship: string
  investment: string
  other: string
  wipPage: string
  family: string
  homePageMetaTagTitle: string
  homePageTitle: string
  homePageSubTitle: string
  getStarted: string
  language: string
  law: string
  getInTouch: string
  interview: string
  interviewQuestionsPageTitle: string
  interviewQuestionsPageSubTitle: string
  interviewQuestionPageMetaTagTitle: string
  interviewQuestionPageMetaTagDescription: string
  history: string
  georgian: string
  restart: string
  languageTicketsTitle: string
  lawTicketsTitle: string
  historyTicketsTitle: string
  languageTestPageTitle: string
  lawTestPageTitle: string
  historyTestPageTitle: string
  startTest: string
  markAsLearned: string
  learned: string
  allTickets: string
  completedTickets: string
  testPassed: string
  testFailed: string
  markTest: string
  testCongratulation: (variables: { percentage: string }) => string
  scoreToPass: (variables: { percentage: string }) => string
  completedTicketsTestMin: (variables: { count: string }) => string
  homePageMetaTagDescription: string
  categoryPageMetaTagTitle: (variables: { category: string }) => string
  categoryPageMetaTagDescription: (variables: { category: string }) => string
  categoryTestPageMetaTagTitle: (variables: { category: string }) => string
  categoryTestPageMetaTagDescription: (variables: {
    category: string
  }) => string
}
