// This file is generated by app/copy/codegen/utils/generateCopy.ts
import { Copy } from './Copy'

import { Injector } from '@lib/utils/template/Injector'

const enCopy: Copy = {
  introduction: `Introduction`,
  education: `Education`,
  origin: `Origin`,
  signIn: `Sign in`,
  account: `Account`,
  work: `Work`,
  residence: `Residence`,
  citizenship: `Citizenship`,
  investment: `Investment`,
  other: `Other`,
  youHaveScored: `You've scored`,
  signInToContinue: `Sign in to continue`,
  wipPage: `This page is a work in progress.`,
  purchase: `Purchase`,
  synchingCheckout: `Synching with checkout...`,
  synchingOrder: `Synching with order...`,
  family: `Family`,
  privacy: `Privacy`,
  purchasePromptTitle: `Unlock Unlimited Access`,
  purchasePromptWithPrice: <R>(
    variables: { price: any },
    inject: Injector<R>,
  ) => inject(`Enhance Your Prep for Only {{price}}`, variables),
  purchasePromptContent: `Upgrade to the lifetime version now for unlimited access to all exam simulations and study materials. Ensure your success on the Georgian citizenship exam with GeorgianCitizen.`,
  continueWithGoogle: `Continue with Google`,
  continueWithFacebook: `Continue with Facebook`,
  emailAddress: `Email address`,
  continue: `Continue`,
  terms: `Terms`,
  yourAccount: `Your account`,
  signOut: `Sign out`,
  withTermsOfService: `Terms of Service`,
  withPrivacyPolicy: `Privacy Policy`,
  agreement: <R>(
    variables: { terms: any; privacy: any },
    inject: Injector<R>,
  ) =>
    inject(
      `By continuing, you agree to our {{terms}} and {{privacy}}.`,
      variables,
    ),
  authTitle: `Sign In or Create Account`,
  homePageMetaTagTitle: `Prepare for Georgian Citizenship Exam: Language, Law, History Guides & Practice Tests`,
  homePageTitle: `Master Your Georgian Citizenship Exam with Confidence!`,
  homePageSubTitle: `Ace Tickets in Language, Law and History`,
  getStarted: `Get Started`,
  language: `Language`,
  law: `Law`,
  getInTouch: `Get in Touch`,
  interview: `Interview`,
  interviewQuestionsPageTitle: `Essential Questions for the Georgian Citizenship Interview`,
  interviewQuestionsPageSubTitle: `Explore a curated list of potential questions with example answers and audio recordings to confidently prepare for your Georgian citizenship interview.`,
  interviewQuestionPageMetaTagTitle: `Georgian Citizenship Interview Questions Guide | Prepare for Success`,
  interviewQuestionPageMetaTagDescription: `Master Georgian citizenship interview questions with our comprehensive guide. Get expert tips, example answers, and prepare confidently for your interview.`,
  history: `History`,
  georgian: `Georgian`,
  restart: `Restart`,
  languageTicketsTitle: `Georgian Language Tickets`,
  lawTicketsTitle: `Georgian Law Tickets`,
  historyTicketsTitle: `Georgian History Tickets`,
  languageTestPageTitle: `Georgian Language Test`,
  lawTestPageTitle: `Georgian Law Test`,
  historyTestPageTitle: `Georgian History Test`,
  startTest: `Start Test`,
  markAsLearned: `mark as learned`,
  learned: `learned`,
  allTickets: `All Tickets`,
  completedTickets: `Completed Tickets`,
  testPassed: `You have passed the test!`,
  testFailed: `You have failed the test :(`,
  markTest: `Review this question after the test`,
  testCongratulation: <R>(
    variables: { percentage: any },
    inject: Injector<R>,
  ) =>
    inject(
      `Congratulations! You've surpassed the {{percentage}} milestone! 🎉 Keep up the great work!`,
      variables,
    ),
  scoreToPass: <R>(variables: { percentage: any }, inject: Injector<R>) =>
    inject(`Score {{percentage}} or above to pass!`, variables),
  completedTicketsTestMin: <R>(
    variables: { count: any },
    inject: Injector<R>,
  ) =>
    inject(
      `You need to mark as completed at least {{count}} tickets to take this test.`,
      variables,
    ),
  homePageMetaTagDescription: `Ace your Georgian Citizenship Exam with our comprehensive study guides, practice tests, and resources tailored for success in Language, Law, and History. Start preparing today!`,
  categoryPageMetaTagTitle: <R>(
    variables: { category: any },
    inject: Injector<R>,
  ) =>
    inject(
      `Prepare for Georgian Citizenship {{category}} Exam: {{category}} Tickets & Practice Tests`,
      variables,
    ),
  categoryPageMetaTagDescription: <R>(
    variables: { category: any },
    inject: Injector<R>,
  ) =>
    inject(
      `Ace your Georgian Citizenship {{category}} Exam with our comprehensive study guides, practice tests, and resources tailored for success in {{category}}. Start preparing today!`,
      variables,
    ),
  categoryTestPageMetaTagTitle: <R>(
    variables: { category: any },
    inject: Injector<R>,
  ) =>
    inject(
      `Test your Georgian Citizenship {{category}} Exam Knowledge`,
      variables,
    ),
  categoryTestPageMetaTagDescription: <R>(
    variables: { category: any },
    inject: Injector<R>,
  ) =>
    inject(
      `Test your Georgian Citizenship {{category}} Exam knowledge with our {{category}} practice tests. Start preparing today!`,
      variables,
    ),
}

export default enCopy
