// This file is generated by app/copy/codegen/utils/generateCopy.ts
import { Copy } from './Copy'

import { Injector } from '@lib/utils/template/Injector'

const kaCopy: Copy = {
  introduction: `შესავალი`,
  education: `Განათლება`,
  origin: `წარმოშობა`,
  signIn: `Შებრძანდით`,
  account: `ანგარიში`,
  work: `მუშაობა`,
  residence: `რეზიდენცია`,
  citizenship: `მოქალაქეობა`,
  investment: `ინვესტიცია`,
  other: `სხვა`,
  youHaveScored: `შენ გაიტანე`,
  signInToContinue: `გასაგრძელებლად შედით სისტემაში`,
  wipPage: `ეს გვერდი მიმდინარე სამუშაოა.`,
  family: `ოჯახი`,
  privacy: `კონფიდენციალურობა`,
  purchasePromptTitle: `განბლოკეთ შეუზღუდავი წვდომა`,
  purchasePromptWithPrice: <R>(
    variables: { price: any },
    inject: Injector<R>,
  ) =>
    inject(`გააძლიერეთ თქვენი მომზადება მხოლოდ {{price}}-ისთვის!`, variables),
  purchasePromptContent: `მზად ხართ სრულად მოემზადოთ საქართველოს მოქალაქეობის გამოცდისთვის? განაახლეთ უვადო ვერსიაზე ახლა და ისიამოვნეთ ტესტის შეუზღუდავი სიმულაციებით, ყველა სასწავლო მასალაზე სრული წვდომით და თქვენი პროგრესის პერსონალიზებული თვალყურის დევნით. ჩადეთ ინვესტიცია თქვენს წარმატებაში და უზრუნველყოთ GeorgianCitizen-ის ყველა ფუნქციის შეუზღუდავი გამოყენება, რათა უზრუნველყოთ გამოცდის დღეს საფუძვლიანად მომზადებული და თავდაჯერებული.`,
  continueWithGoogle: `განაგრძეთ Google-თან`,
  continueWithFacebook: `განაგრძეთ Facebook-ით`,
  emailAddress: `Ელექტრონული მისამართი`,
  continue: `განაგრძეთ`,
  terms: `Ვადები`,
  yourAccount: `Თქვენი ანგარიში`,
  signOut: `Სისტემიდან გამოსვლა`,
  withTermsOfService: `Მომსახურების პირობები`,
  withPrivacyPolicy: `Კონფიდენციალურობის პოლიტიკა`,
  agreement: <R>(
    variables: { terms: any; privacy: any },
    inject: Injector<R>,
  ) =>
    inject(
      `გაგრძელებით თქვენ ეთანხმებით ჩვენს {{terms}}-სა და {{privacy}}-ს.`,
      variables,
    ),
  authTitle: `შედით ან შექმენით ანგარიში`,
  homePageMetaTagTitle: `მოემზადეთ საქართველოს მოქალაქეობის გამოცდისთვის: ენა, სამართალი, ისტორიის სახელმძღვანელო და პრაქტიკული ტესტები`,
  homePageTitle: `დაეუფლეთ საქართველოს მოქალაქეობის გამოცდას თავდაჯერებულად!`,
  homePageSubTitle: `Ace ბილეთები ენაში, სამართალში, ისტორიაში`,
  getStarted: `Დაიწყე`,
  language: `Ენა`,
  law: `Კანონი`,
  getInTouch: `Შემეხმიანე`,
  interview: `ინტერვიუ`,
  interviewQuestionsPageTitle: `არსებითი კითხვები საქართველოს მოქალაქეობის ინტერვიუსთვის`,
  interviewQuestionsPageSubTitle: `გამოიკვლიეთ პოტენციური კითხვების კურირებული სია პასუხების მაგალითებით და აუდიო ჩანაწერებით, რათა თავდაჯერებულად მოემზადოთ საქართველოს მოქალაქეობის გასაუბრებისთვის.`,
  interviewQuestionPageMetaTagTitle: `საქართველოს მოქალაქეობის გასაუბრების კითხვები გზამკვლევი | მოემზადეთ წარმატებისთვის`,
  interviewQuestionPageMetaTagDescription: `დაეუფლეთ საქართველოს მოქალაქეობის გასაუბრების კითხვებს ჩვენს ყოვლისმომცველ სახელმძღვანელოსთან ერთად. მიიღეთ ექსპერტთა რჩევები, მაგალითები პასუხები და მოემზადეთ თავდაჯერებულად თქვენი ინტერვიუსთვის.`,
  history: `ისტორია`,
  georgian: `ქართული`,
  restart: `Რესტარტი`,
  languageTicketsTitle: `ქართული ენის ბილეთები`,
  lawTicketsTitle: `ქართული სამართლის ბილეთები`,
  historyTicketsTitle: `საქართველოს ისტორიის ბილეთები`,
  languageTestPageTitle: `ქართული ენის ტესტი`,
  lawTestPageTitle: `საქართველოს სამართლის ტესტი`,
  historyTestPageTitle: `საქართველოს ისტორიის ტესტი`,
  startTest: `ტესტის დაწყება`,
  markAsLearned: `მონიშნე როგორც ნასწავლი`,
  learned: `ისწავლა`,
  allTickets: `ყველა ბილეთი`,
  completedTickets: `დასრულებული ბილეთები`,
  testPassed: `თქვენ გაიარეთ ტესტი!`,
  testFailed: `გამოცდა ჩააბარე :(`,
  markTest: `გადახედეთ ამ კითხვას ტესტის შემდეგ`,
  testCongratulation: <R>(
    variables: { percentage: any },
    inject: Injector<R>,
  ) =>
    inject(
      `გილოცავ! თქვენ გადააჭარბეთ {{percentage}} ეტაპს! 🎉 განაგრძეთ შესანიშნავი სამუშაო!`,
      variables,
    ),
  scoreToPass: <R>(variables: { percentage: any }, inject: Injector<R>) =>
    inject(`ჩასაბარებლად ქულა {{percentage}} ან მეტი!`, variables),
  completedTicketsTestMin: <R>(
    variables: { count: any },
    inject: Injector<R>,
  ) =>
    inject(
      `თქვენ უნდა მონიშნოთ დასრულებულად მინიმუმ {{count}} ბილეთი ამ ტესტის გასავლელად.`,
      variables,
    ),
  homePageMetaTagDescription: `გაიარეთ თქვენი საქართველოს მოქალაქეობის გამოცდა ჩვენი ყოვლისმომცველი სასწავლო სახელმძღვანელოებით, პრაქტიკული ტესტებით და რესურსებით, რომლებიც მორგებულია ენის, სამართლისა და ისტორიაში წარმატებისთვის. დაიწყეთ მზადება დღესვე!`,
  categoryPageMetaTagTitle: <R>(
    variables: { category: any },
    inject: Injector<R>,
  ) =>
    inject(
      `მოემზადეთ საქართველოს მოქალაქეობის {{category}} გამოცდისთვის: {{category}} ბილეთები და პრაქტიკული ტესტები`,
      variables,
    ),
  categoryPageMetaTagDescription: <R>(
    variables: { category: any },
    inject: Injector<R>,
  ) =>
    inject(
      `გაიარეთ თქვენი საქართველოს მოქალაქეობის {{category}} გამოცდა ჩვენი ყოვლისმომცველი სასწავლო სახელმძღვანელოებით, პრაქტიკული ტესტებით და რესურსებით, რომლებიც მორგებულია წარმატებისთვის {{category}}-ში. დაიწყეთ მზადება დღესვე!`,
      variables,
    ),
  categoryTestPageMetaTagTitle: <R>(
    variables: { category: any },
    inject: Injector<R>,
  ) =>
    inject(
      `შეამოწმეთ თქვენი საქართველოს მოქალაქეობის {{category}} გამოცდის ცოდნა`,
      variables,
    ),
  categoryTestPageMetaTagDescription: <R>(
    variables: { category: any },
    inject: Injector<R>,
  ) =>
    inject(
      `შეამოწმეთ თქვენი საქართველოს მოქალაქეობის {{category}} გამოცდის ცოდნა ჩვენი {{category}} პრაქტიკული ტესტებით. დაიწყეთ მზადება დღესვე!`,
      variables,
    ),
}

export default kaCopy
